"""Input-validation guards for the RAG layer.

RAG inputs flow from two semi-trusted sources:
  1. The feature request / queries derived from agent state (user-influenced).
  2. Document content pulled from the DB (generated by LLM agents).

These guards enforce hard caps so a malicious or malformed input cannot:
  - exhaust memory/CPU via an enormous query or an unbounded *k*
  - smuggle an unexpected corpus name into a parameterised query
  - feed multi-megabyte chunks into an LLM (cost-blowup / context overflow)

All limits are deliberately generous; they are a safety net, not a policy.
"""

from __future__ import annotations

import re

# Hard caps — tuned to be far above any legitimate use.
MAX_QUERY_CHARS = 8_000
MAX_K = 100
MAX_DOC_CHARS = 100_000  # per chunk, before indexing
MAX_CONTENT_TO_LLM = 4_000  # truncate content fed into extraction/judge prompts

# Corpus names are used in parameterised SQL, but we still allowlist the shape
# so they can be safely embedded in metrics labels and log lines.
_CORPUS_RE = re.compile(r"^[a-z0-9_-]{1,64}$")


class RagInputError(ValueError):
    """Raised when a RAG input violates a safety guard."""

    def __init__(self, reason: str, message: str) -> None:
        self.reason = reason
        super().__init__(message)


def _record_rejection(reason: str) -> None:
    try:
        from src.observability.tracing import rag_rejected_counter

        rag_rejected_counter.add(1, {"reason": reason})
    except Exception:
        pass


def validate_query(query: str) -> str:
    """Return a sanitised query or raise RagInputError.

    Empty/whitespace queries are rejected; over-long queries are rejected
    rather than silently truncated so the caller notices the misuse.
    """
    if not isinstance(query, str) or not query.strip():
        _record_rejection("empty_query")
        raise RagInputError("empty_query", "RAG query must be a non-empty string")
    if len(query) > MAX_QUERY_CHARS:
        _record_rejection("query_too_long")
        raise RagInputError(
            "query_too_long",
            f"RAG query exceeds {MAX_QUERY_CHARS} chars (got {len(query)})",
        )
    return query


def validate_k(k: int) -> int:
    """Clamp *k* into [1, MAX_K]; reject non-integers."""
    if not isinstance(k, int) or isinstance(k, bool):
        _record_rejection("invalid_k")
        raise RagInputError("invalid_k", f"k must be an int (got {type(k).__name__})")
    if k < 1:
        _record_rejection("invalid_k")
        raise RagInputError("invalid_k", f"k must be >= 1 (got {k})")
    return min(k, MAX_K)


def validate_corpus(corpus: str | None) -> str | None:
    """Validate a corpus name against the allowlist pattern (None is allowed)."""
    if corpus is None:
        return None
    if not _CORPUS_RE.match(corpus):
        _record_rejection("invalid_corpus")
        raise RagInputError(
            "invalid_corpus",
            f"corpus name must match {_CORPUS_RE.pattern!r} (got {corpus!r})",
        )
    return corpus


def truncate_for_llm(content: str, limit: int = MAX_CONTENT_TO_LLM) -> str:
    """Truncate document content before embedding it in an LLM prompt."""
    if len(content) <= limit:
        return content
    return content[:limit]
